/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __XDP_PING_SKEL_H__
#define __XDP_PING_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

#define BPF_SKEL_SUPPORTS_MAP_AUTO_ATTACH 1

struct xdp_ping {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_program *xdp_tx_ping;
	} progs;
	struct {
		struct bpf_link *xdp_tx_ping;
	} links;

#ifdef __cplusplus
	static inline struct xdp_ping *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct xdp_ping *open_and_load();
	static inline int load(struct xdp_ping *skel);
	static inline int attach(struct xdp_ping *skel);
	static inline void detach(struct xdp_ping *skel);
	static inline void destroy(struct xdp_ping *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
xdp_ping__destroy(struct xdp_ping *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
xdp_ping__create_skeleton(struct xdp_ping *obj);

static inline struct xdp_ping *
xdp_ping__open_opts(const struct bpf_object_open_opts *opts)
{
	struct xdp_ping *obj;
	int err;

	obj = (struct xdp_ping *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = xdp_ping__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	xdp_ping__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct xdp_ping *
xdp_ping__open(void)
{
	return xdp_ping__open_opts(NULL);
}

static inline int
xdp_ping__load(struct xdp_ping *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct xdp_ping *
xdp_ping__open_and_load(void)
{
	struct xdp_ping *obj;
	int err;

	obj = xdp_ping__open();
	if (!obj)
		return NULL;
	err = xdp_ping__load(obj);
	if (err) {
		xdp_ping__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
xdp_ping__attach(struct xdp_ping *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
xdp_ping__detach(struct xdp_ping *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *xdp_ping__elf_bytes(size_t *sz);

static inline int
xdp_ping__create_skeleton(struct xdp_ping *obj)
{
	struct bpf_object_skeleton *s;
	struct bpf_map_skeleton *map __attribute__((unused));
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "xdp_ping";
	s->obj = &obj->obj;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "xdp_tx_ping";
	s->progs[0].prog = &obj->progs.xdp_tx_ping;
	s->progs[0].link = &obj->links.xdp_tx_ping;

	s->data = xdp_ping__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *xdp_ping__elf_bytes(size_t *sz)
{
	static const char data[] __attribute__((__aligned__(8))) = "\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\xd0\x0b\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x18\0\
\x01\0\xb7\0\0\0\x03\0\0\0\x95\0\0\0\0\0\0\0\x47\x50\x4c\0\x01\x11\x01\x25\x25\
\x13\x05\x03\x25\x72\x17\x10\x17\x1b\x25\x11\x1b\x12\x06\x73\x17\0\0\x02\x34\0\
\x03\x25\x49\x13\x3f\x19\x3a\x0b\x3b\x0b\x02\x18\0\0\x03\x01\x01\x49\x13\0\0\
\x04\x21\0\x49\x13\x37\x0b\0\0\x05\x24\0\x03\x25\x3e\x0b\x0b\x0b\0\0\x06\x24\0\
\x03\x25\x0b\x0b\x3e\x0b\0\0\x07\x04\x01\x49\x13\x03\x25\x0b\x0b\x3a\x0b\x3b\
\x05\0\0\x08\x28\0\x03\x25\x1c\x0f\0\0\x09\x2e\x01\x11\x1b\x12\x06\x40\x18\x7a\
\x19\x03\x25\x3a\x0b\x3b\x0b\x27\x19\x49\x13\x3f\x19\0\0\x0a\x05\0\x03\x25\x3a\
\x0b\x3b\x0b\x49\x13\0\0\x0b\x0f\0\x49\x13\0\0\x0c\x13\x01\x03\x25\x0b\x0b\x3a\
\x0b\x3b\x05\0\0\x0d\x0d\0\x03\x25\x49\x13\x3a\x0b\x3b\x05\x38\x0b\0\0\x0e\x16\
\0\x49\x13\x03\x25\x3a\x0b\x3b\x0b\0\0\0\xc9\0\0\0\x05\0\x01\x08\0\0\0\0\x01\0\
\x1d\0\x01\x08\0\0\0\0\0\0\0\x02\x01\x10\0\0\0\x08\0\0\0\x02\x03\x2e\0\0\0\0\
\x06\x02\xa1\0\x03\x3a\0\0\0\x04\x3e\0\0\0\x04\0\x05\x04\x06\x01\x06\x05\x08\
\x07\x07\x5c\0\0\0\x0c\x04\x01\xc2\x18\x08\x07\0\x08\x08\x01\x08\x09\x02\x08\
\x0a\x03\x08\x0b\x04\0\x05\x06\x07\x04\x09\x01\x10\0\0\0\x01\x5a\x0d\0\x09\x78\
\0\0\0\x0a\x0f\0\x09\x7c\0\0\0\0\x05\x0e\x05\x04\x0b\x81\0\0\0\x0c\x17\x18\x01\
\xcd\x18\x0d\x10\xc4\0\0\0\x01\xce\x18\0\x0d\x12\xc4\0\0\0\x01\xcf\x18\x04\x0d\
\x13\xc4\0\0\0\x01\xd0\x18\x08\x0d\x14\xc4\0\0\0\x01\xd2\x18\x0c\x0d\x15\xc4\0\
\0\0\x01\xd3\x18\x10\x0d\x16\xc4\0\0\0\x01\xd5\x18\x14\0\x0e\x5c\0\0\0\x11\x02\
\x1b\0\x64\0\0\0\x05\0\0\0\0\0\0\0\x27\0\0\0\x3a\0\0\0\x61\0\0\0\x6a\0\0\0\x6f\
\0\0\0\x83\0\0\0\x90\0\0\0\x9c\0\0\0\xa5\0\0\0\xae\0\0\0\xb5\0\0\0\xc2\0\0\0\
\xcd\0\0\0\xd9\0\0\0\xdd\0\0\0\xe1\0\0\0\xe6\0\0\0\xec\0\0\0\xf5\0\0\0\xff\0\0\
\0\x0f\x01\0\0\x1e\x01\0\0\x2d\x01\0\0\x55\x62\x75\x6e\x74\x75\x20\x63\x6c\x61\
\x6e\x67\x20\x76\x65\x72\x73\x69\x6f\x6e\x20\x31\x38\x2e\x31\x2e\x33\x20\x28\
\x31\x75\x62\x75\x6e\x74\x75\x31\x29\0\x73\x72\x63\x2f\x78\x64\x70\x5f\x70\x69\
\x6e\x67\x2e\x62\x70\x66\x2e\x63\0\x2f\x68\x6f\x6d\x65\x2f\x73\x6f\x61\x72\x65\
\x73\x2f\x44\x6f\x63\x75\x6d\x65\x6e\x74\x73\x2f\x47\x69\x74\x68\x75\x62\x2f\
\x78\x64\x70\x5f\x70\x69\x6e\x67\0\x5f\x6c\x69\x63\x65\x6e\x73\x65\0\x63\x68\
\x61\x72\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\x5a\x45\x5f\x54\x59\x50\x45\
\x5f\x5f\0\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x69\x6e\x74\0\x58\x44\x50\x5f\
\x41\x42\x4f\x52\x54\x45\x44\0\x58\x44\x50\x5f\x44\x52\x4f\x50\0\x58\x44\x50\
\x5f\x50\x41\x53\x53\0\x58\x44\x50\x5f\x54\x58\0\x58\x44\x50\x5f\x52\x45\x44\
\x49\x52\x45\x43\x54\0\x78\x64\x70\x5f\x61\x63\x74\x69\x6f\x6e\0\x78\x64\x70\
\x5f\x74\x78\x5f\x70\x69\x6e\x67\0\x69\x6e\x74\0\x63\x74\x78\0\x64\x61\x74\x61\
\0\x5f\x5f\x75\x33\x32\0\x64\x61\x74\x61\x5f\x65\x6e\x64\0\x64\x61\x74\x61\x5f\
\x6d\x65\x74\x61\0\x69\x6e\x67\x72\x65\x73\x73\x5f\x69\x66\x69\x6e\x64\x65\x78\
\0\x72\x78\x5f\x71\x75\x65\x75\x65\x5f\x69\x6e\x64\x65\x78\0\x65\x67\x72\x65\
\x73\x73\x5f\x69\x66\x69\x6e\x64\x65\x78\0\x78\x64\x70\x5f\x6d\x64\0\x14\0\0\0\
\x05\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\
\0\x0c\x01\0\0\x0c\x01\0\0\xf0\0\0\0\0\0\0\0\0\0\0\x02\x02\0\0\0\x01\0\0\0\x06\
\0\0\x04\x18\0\0\0\x08\0\0\0\x03\0\0\0\0\0\0\0\x0d\0\0\0\x03\0\0\0\x20\0\0\0\
\x16\0\0\0\x03\0\0\0\x40\0\0\0\x20\0\0\0\x03\0\0\0\x60\0\0\0\x30\0\0\0\x03\0\0\
\0\x80\0\0\0\x3f\0\0\0\x03\0\0\0\xa0\0\0\0\x4e\0\0\0\0\0\0\x08\x04\0\0\0\x54\0\
\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\0\x01\0\0\x0d\x06\0\0\0\x61\0\0\0\x01\
\0\0\0\x65\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\x01\x69\0\0\0\x01\0\0\x0c\x05\0\0\
\0\xc6\0\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x08\0\0\
\0\x0a\0\0\0\x04\0\0\0\xcb\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\xdf\0\0\0\0\0\0\
\x0e\x09\0\0\0\x01\0\0\0\xe8\0\0\0\x01\0\0\x0f\0\0\0\0\x0b\0\0\0\0\0\0\0\x04\0\
\0\0\0\x78\x64\x70\x5f\x6d\x64\0\x64\x61\x74\x61\0\x64\x61\x74\x61\x5f\x65\x6e\
\x64\0\x64\x61\x74\x61\x5f\x6d\x65\x74\x61\0\x69\x6e\x67\x72\x65\x73\x73\x5f\
\x69\x66\x69\x6e\x64\x65\x78\0\x72\x78\x5f\x71\x75\x65\x75\x65\x5f\x69\x6e\x64\
\x65\x78\0\x65\x67\x72\x65\x73\x73\x5f\x69\x66\x69\x6e\x64\x65\x78\0\x5f\x5f\
\x75\x33\x32\0\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x69\x6e\x74\0\x63\x74\x78\0\
\x69\x6e\x74\0\x78\x64\x70\x5f\x74\x78\x5f\x70\x69\x6e\x67\0\x78\x64\x70\0\x2f\
\x68\x6f\x6d\x65\x2f\x73\x6f\x61\x72\x65\x73\x2f\x44\x6f\x63\x75\x6d\x65\x6e\
\x74\x73\x2f\x47\x69\x74\x68\x75\x62\x2f\x78\x64\x70\x5f\x70\x69\x6e\x67\x2f\
\x73\x72\x63\x2f\x78\x64\x70\x5f\x70\x69\x6e\x67\x2e\x62\x70\x66\x2e\x63\0\x20\
\x20\x20\x20\x72\x65\x74\x75\x72\x6e\x20\x58\x44\x50\x5f\x54\x58\x3b\0\x63\x68\
\x61\x72\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\x5a\x45\x5f\x54\x59\x50\x45\
\x5f\x5f\0\x5f\x6c\x69\x63\x65\x6e\x73\x65\0\x6c\x69\x63\x65\x6e\x73\x65\0\x9f\
\xeb\x01\0\x20\0\0\0\0\0\0\0\x14\0\0\0\x14\0\0\0\x1c\0\0\0\x30\0\0\0\0\0\0\0\
\x08\0\0\0\x75\0\0\0\x01\0\0\0\0\0\0\0\x07\0\0\0\x10\0\0\0\x75\0\0\0\x01\0\0\0\
\0\0\0\0\x79\0\0\0\xb3\0\0\0\x05\x3c\0\0\x0c\0\0\0\xff\xff\xff\xff\x04\0\x08\0\
\x08\x7c\x0b\0\x14\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x89\0\0\0\
\x05\0\x08\0\x69\0\0\0\x08\x01\x01\xfb\x0e\x0d\0\x01\x01\x01\x01\0\0\0\x01\0\0\
\x01\x01\x01\x1f\x03\0\0\0\0\x27\0\0\0\x3a\0\0\0\x03\x01\x1f\x02\x0f\x05\x1e\
\x03\x53\0\0\0\0\x1a\x83\x44\x45\x89\x54\x1f\xb7\x07\xba\x09\x0c\xff\x4a\x7d\
\xab\x66\0\0\0\x01\xad\x6e\x63\x18\x59\x68\xe7\x1a\x1e\xdc\x77\x67\xbb\x1d\x26\
\x1e\x6c\0\0\0\x02\xb8\x10\xf2\x70\x73\x3e\x10\x63\x19\xb6\x7e\xf5\x12\xc6\x24\
\x6e\x04\0\x05\x05\x0a\0\x09\x02\0\0\0\0\0\0\0\0\x03\x0e\x01\x02\x02\0\x01\x01\
\x2f\x68\x6f\x6d\x65\x2f\x73\x6f\x61\x72\x65\x73\x2f\x44\x6f\x63\x75\x6d\x65\
\x6e\x74\x73\x2f\x47\x69\x74\x68\x75\x62\x2f\x78\x64\x70\x5f\x70\x69\x6e\x67\0\
\x2f\x75\x73\x72\x2f\x69\x6e\x63\x6c\x75\x64\x65\x2f\x6c\x69\x6e\x75\x78\0\x2f\
\x75\x73\x72\x2f\x69\x6e\x63\x6c\x75\x64\x65\x2f\x61\x73\x6d\x2d\x67\x65\x6e\
\x65\x72\x69\x63\0\x73\x72\x63\x2f\x78\x64\x70\x5f\x70\x69\x6e\x67\x2e\x62\x70\
\x66\x2e\x63\0\x62\x70\x66\x2e\x68\0\x69\x6e\x74\x2d\x6c\x6c\x36\x34\x2e\x68\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xbc\0\0\0\x04\0\xf1\
\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\x03\0\x05\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\
\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x0a\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x03\0\x0b\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\
\x11\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x13\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x03\0\x15\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x78\0\0\0\x12\
\0\x03\0\0\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x92\0\0\0\x11\0\x04\0\0\0\0\0\0\0\0\
\0\x04\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\x03\0\0\0\x03\0\0\0\x11\0\0\0\0\0\0\0\
\x03\0\0\0\x04\0\0\0\x15\0\0\0\0\0\0\0\x03\0\0\0\x08\0\0\0\x1f\0\0\0\0\0\0\0\
\x03\0\0\0\x06\0\0\0\x08\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x0c\0\0\0\0\0\0\0\
\x03\0\0\0\x05\0\0\0\x10\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x14\0\0\0\0\0\0\0\
\x03\0\0\0\x05\0\0\0\x18\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x1c\0\0\0\0\0\0\0\
\x03\0\0\0\x05\0\0\0\x20\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x24\0\0\0\0\0\0\0\
\x03\0\0\0\x05\0\0\0\x28\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x2c\0\0\0\0\0\0\0\
\x03\0\0\0\x05\0\0\0\x30\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x34\0\0\0\0\0\0\0\
\x03\0\0\0\x05\0\0\0\x38\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x3c\0\0\0\0\0\0\0\
\x03\0\0\0\x05\0\0\0\x40\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x44\0\0\0\0\0\0\0\
\x03\0\0\0\x05\0\0\0\x48\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x4c\0\0\0\0\0\0\0\
\x03\0\0\0\x05\0\0\0\x50\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x54\0\0\0\0\0\0\0\
\x03\0\0\0\x05\0\0\0\x58\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x5c\0\0\0\0\0\0\0\
\x03\0\0\0\x05\0\0\0\x60\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\x64\0\0\0\0\0\0\0\
\x03\0\0\0\x05\0\0\0\x08\0\0\0\0\0\0\0\x02\0\0\0\x0b\0\0\0\x10\0\0\0\0\0\0\0\
\x02\0\0\0\x02\0\0\0\x1c\x01\0\0\0\0\0\0\x04\0\0\0\x0b\0\0\0\x2c\0\0\0\0\0\0\0\
\x04\0\0\0\x02\0\0\0\x40\0\0\0\0\0\0\0\x04\0\0\0\x02\0\0\0\x14\0\0\0\0\0\0\0\
\x03\0\0\0\x07\0\0\0\x18\0\0\0\0\0\0\0\x02\0\0\0\x02\0\0\0\x22\0\0\0\0\0\0\0\
\x03\0\0\0\x09\0\0\0\x26\0\0\0\0\0\0\0\x03\0\0\0\x09\0\0\0\x2a\0\0\0\0\0\0\0\
\x03\0\0\0\x09\0\0\0\x36\0\0\0\0\0\0\0\x03\0\0\0\x09\0\0\0\x4b\0\0\0\0\0\0\0\
\x03\0\0\0\x09\0\0\0\x60\0\0\0\0\0\0\0\x03\0\0\0\x09\0\0\0\x7d\0\0\0\0\0\0\0\
\x02\0\0\0\x02\0\0\0\x0a\x0b\0\x2e\x64\x65\x62\x75\x67\x5f\x61\x62\x62\x72\x65\
\x76\0\x2e\x74\x65\x78\x74\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\x2e\x65\x78\x74\0\
\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\x67\x5f\x73\x74\x72\x5f\x6f\x66\x66\x73\
\x65\x74\x73\0\x2e\x64\x65\x62\x75\x67\x5f\x73\x74\x72\0\x2e\x64\x65\x62\x75\
\x67\x5f\x6c\x69\x6e\x65\x5f\x73\x74\x72\0\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\
\x67\x5f\x61\x64\x64\x72\0\x78\x64\x70\0\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\
\x67\x5f\x69\x6e\x66\x6f\0\x78\x64\x70\x5f\x74\x78\x5f\x70\x69\x6e\x67\0\x2e\
\x6c\x6c\x76\x6d\x5f\x61\x64\x64\x72\x73\x69\x67\0\x5f\x6c\x69\x63\x65\x6e\x73\
\x65\0\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\x67\x5f\x6c\x69\x6e\x65\0\x2e\x72\
\x65\x6c\x2e\x64\x65\x62\x75\x67\x5f\x66\x72\x61\x6d\x65\0\x78\x64\x70\x5f\x70\
\x69\x6e\x67\x2e\x62\x70\x66\x2e\x63\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\
\x79\x6d\x74\x61\x62\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xcb\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\xea\x0a\0\0\0\0\0\0\xe4\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\x0f\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x64\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\x10\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x93\0\0\0\x01\0\
\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x50\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x01\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x54\0\0\0\0\0\0\0\xbd\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x6c\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x11\x01\0\0\0\0\0\0\xcd\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\x68\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x48\x08\0\0\
\0\0\0\0\x40\0\0\0\0\0\0\0\x17\0\0\0\x06\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\
\0\0\x26\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xde\x01\0\0\0\0\0\0\
\x68\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x22\0\0\0\
\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x88\x08\0\0\0\0\0\0\x80\x01\0\0\0\
\0\0\0\x17\0\0\0\x08\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x39\0\0\0\x01\0\
\0\0\x30\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x46\x02\0\0\0\0\0\0\x34\x01\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\x58\0\0\0\x01\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x7a\x03\0\0\0\0\0\0\x18\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x54\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\x08\x0a\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\x17\0\0\0\x0b\0\0\0\x08\0\0\
\0\0\0\0\0\x10\0\0\0\0\0\0\0\xdf\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x94\x03\0\0\0\0\0\0\x14\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\xdb\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x28\x0a\0\
\0\0\0\0\0\x10\0\0\0\0\0\0\0\x17\0\0\0\x0d\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\
\0\0\0\x19\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xa8\x05\0\0\0\0\0\0\
\x50\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x15\0\0\0\
\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x38\x0a\0\0\0\0\0\0\x20\0\0\0\0\0\
\0\0\x17\0\0\0\x0f\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\xaf\0\0\0\x01\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xf8\x05\0\0\0\0\0\0\x28\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xab\0\0\0\x09\0\0\0\x40\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x58\x0a\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\x17\0\0\0\x11\0\0\0\
\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x9f\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x20\x06\0\0\0\0\0\0\x8d\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x9b\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x78\
\x0a\0\0\0\0\0\0\x70\0\0\0\0\0\0\0\x17\0\0\0\x13\0\0\0\x08\0\0\0\0\0\0\0\x10\0\
\0\0\0\0\0\0\x44\0\0\0\x01\0\0\0\x30\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xad\x06\0\0\
\0\0\0\0\x77\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\
\x84\0\0\0\x03\x4c\xff\x6f\0\0\0\x80\0\0\0\0\0\0\0\0\0\0\0\0\xe8\x0a\0\0\0\0\0\
\0\x02\0\0\0\0\0\0\0\x17\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xd3\0\
\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x28\x07\0\0\0\0\0\0\x20\x01\0\0\
\0\0\0\0\x01\0\0\0\x0a\0\0\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0";

	*sz = sizeof(data) - 1;
	return (const void *)data;
}

#ifdef __cplusplus
struct xdp_ping *xdp_ping::open(const struct bpf_object_open_opts *opts) { return xdp_ping__open_opts(opts); }
struct xdp_ping *xdp_ping::open_and_load() { return xdp_ping__open_and_load(); }
int xdp_ping::load(struct xdp_ping *skel) { return xdp_ping__load(skel); }
int xdp_ping::attach(struct xdp_ping *skel) { return xdp_ping__attach(skel); }
void xdp_ping::detach(struct xdp_ping *skel) { xdp_ping__detach(skel); }
void xdp_ping::destroy(struct xdp_ping *skel) { xdp_ping__destroy(skel); }
const void *xdp_ping::elf_bytes(size_t *sz) { return xdp_ping__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
xdp_ping__assert(struct xdp_ping *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __XDP_PING_SKEL_H__ */
